[package]
name = "komplexity"
version = "0.1.0"
authors = ["Erik Clarke <erikclarke@fastmail.com>"]

[dependencies]
bio = "*"
clap = {version="2.*", features=["yaml"]}
fnv = "1.0"
itertools = "*"
rayon="*"

