[package]
name = "komplexity"
version = "0.3.0"
authors = ["Erik Clarke <erikclarke@fastmail.com>"]

[dependencies]
bio = "~0.14"
clap = "~2.24"
fnv = "~1.0"

[[bin]]
name = "kz"
path = "src/main.rs"

